export const genres = [
//   {key: 'Movies', title: 'Movies', id: 1},
//   {key: 'WebSeries', title: 'Web Series', id: 2},
  {key: 'Action', title: 'Action', id: 28},
  {key: 'Adventure', title: 'Adventure', id: 12},
  {key: 'Animation', title: 'Animation', id: 16},
  {key: 'Comedy', title: 'Comedy', id: 35},
  {key: 'Crime', title: 'Crime', id: 80},
  {key: 'Documentary', title: 'Documentary', id: 99},
  {key: 'Drama', title: 'Drama', id: 18},
  {key: 'Family', title: 'Family', id: 10751},
  {key: 'Fantasy', title: 'Fantasy', id: 14},
  {key: 'History', title: 'History', id: 36},
  {key: 'Horror', title: 'Horror', id: 27},
  {key: 'Music', title: 'Music', id: 10402},
  {key: 'Mystery', title: 'Mystery', id: 9648},
  {key: 'Romance', title: 'Romance', id: 10749},
  {key: 'ScienceFiction', title: 'Science Fiction', id: 878},
  {key: 'TVMovie', title: 'TV Movie', id: 10770},
  {key: 'Thriller', title: 'Thriller', id: 53},
  {key: 'War', title: 'War', id: 10752},
  {key: 'Western', title: 'Western', id: 37},
];
