export const TYPE = {
  GET_GENRE_START: 'GET_GENRE_START',
  GET_GENRE_SUCCESS: 'GET_GENRE_SUCCESS',
  GET_GENRE_FAILURE: 'GET_GENRE_FAILURE',

  GET_TRENDING_ALL_START: 'GET_TRENDING_ALL_START',
  GET_TRENDING_ALL_SUCCESS: 'GET_TRENDING_ALL_SUCCESS',
  GET_TRENDING_ALL_FAILURE: 'GET_TRENDING_ALL_FAILURE',

  GET_TRENDING_MOVIES_START: 'GET_TRENDING_MOVIES_START',
  GET_TRENDING_MOVIES_SUCCESS: 'GET_TRENDING_MOVIES_SUCCESS',
  GET_TRENDING_MOVIES_FAILURE: 'GET_TRENDING_MOVIES_FAILURE',

  GET_TRENDING_SERIES_START: 'GET_TRENDING_SERIES_START',
  GET_TRENDING_SERIES_SUCCESS: 'GET_TRENDING_SERIES_SUCCESS',
  GET_TRENDING_SERIES_FAILURE: 'GET_TRENDING_SERIES_FAILURE',

  GET_MOVIES_BY_GENRES: 'GET_MOVIES_BY_GENRES',
  GET_MOVIES_BY_GENRES_SUCCESS: 'GET_MOVIES_BY_GENRES_SUCCESS',
  GET_MOVIES_BY_GENRES_FAILURE: 'GET_MOVIES_BY_GENRES_FAILURE',

  GET_DATA_BY_SEARCH: 'GET_DATA_BY_SEARCH',
  GET_DATA_BY_SEARCH_SUCCESS: 'GET_DATA_BY_SEARCH_SUCCESS',
  GET_DATA_BY_SEARCH_FAILURE: 'GET_DATA_BY_SEARCH_FAILURE',

  //<------------movieDetails----------->//
  GET_DETAILS: 'GET_DETAILS',
  GET_DETAILS_SUCCESS: 'GET_DETAILS_SUCCESS',
  GET_DETAILS_FAILURE: 'GET_DETAILS_FAILURE',

  GET_TRAILER: 'GET_TRAILER',
  GET_TRAILER_SUCCESS: 'GET_TRAILER_SUCCESS',
  GET_TRAILER_FAILURE: 'GET_TRAILER_FAILURE',

  GET_CAST: 'GET_CAST',
  GET_CAST_SUCCESS: 'GET_CAST_SUCCESS',
  GET_CAST_FAILURE: 'GET_CAST_FAILURE',

  GET_IMAGES: 'GET_IMAGES',
  GET_IMAGES_SUCCESS: 'GET_IMAGES_SUCCESS',
  GET_IMAGES_FAILURE: 'GET_IMAGES_FAILURE',
};
