export const TYPE = {
  GET_GENRE_START: 'GET_GENRE_START',
  GET_GENRE_SUCCESS: 'GET_GENRE_SUCCESS',
  GET_GENRE_FAILURE: 'GET_GENRE_FAILURE',

  GET_TRENDING_ALL_START: 'GET_TRENDING_ALL_START',
  GET_TRENDING_ALL_SUCCESS: 'GET_TRENDING_ALL_SUCCESS',
  GET_TRENDING_ALL_FAILURE: 'GET_TRENDING_ALL_FAILURE',

  GET_TRENDING_MOVIES_START: 'GET_TRENDING_MOVIES_START',
  GET_TRENDING_MOVIES_SUCCESS: 'GET_TRENDING_MOVIES_SUCCESS',
  GET_TRENDING_MOVIES_FAILURE: 'GET_TRENDING_MOVIES_FAILURE',

  GET_TRENDING_SERIES_START: 'GET_TRENDING_SERIES_START',
  GET_TRENDING_SERIES_SUCCESS: 'GET_TRENDING_SERIES_SUCCESS',
  GET_TRENDING_SERIES_FAILURE: 'GET_TRENDING_SERIES_FAILURE',
};
